FROM python:3.7-buster

RUN apt-get update \
    && apt-get install gcc -y \
    && apt-get clean

COPY ./requirements.txt .
RUN pip install --upgrade pip
RUN pip install -r ./requirements.txt


RUN mkdir /app 
WORKDIR /app

EXPOSE 8000

ENTRYPOINT ["uvicorn"]
